services:
  app:
    build:
      context:   .
    command:     scrapyd
    depends_on:
      - elasticsearch
      - splash
    image:       zwilson/jobs
    volumes:
      - ./app:/usr/src/app:rw
      - ./configs/app/scrapy.cfg:/usr/src/scrapy.cfg:ro
      - ./configs/app/scrapyd.conf:/usr/src/scrapyd.conf:ro
      - ./data/app:/usr/src/data:rw
      - ./logs/app:/usr/src/logs:rw
    ports:
      - 6800:6800
  elasticsearch:
    environment:
      - xpack.monitoring.collection.enabled=true
    image:       docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  splash:
    image:       scrapinghub/splash
    ports:
      - 8050:8050
  kibana:
    depends_on:
      - elasticsearch
    image:       docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - 5601:5601
  proxy:
    image: nginx
    ports:
      - 80:5602
    restart: always
    volumes:
      - ./configs/proxy/default.conf:/etc/nginx/conf.d/default.conf
version:         '3.6'
