version: "3.6"
services:
  app:
    image: zwilson/jobs
    build: .
    depends_on:
      - splash
      - elasticsearch
    volumes:
      - ./app:/usr/src/app
      - ./configs/scrapy/scrapy.cfg:/usr/src/scrapy.cfg
      - ./items:/usr/src/items
      - ./configs/scrapyd/scrapyd.conf
    command: scrapyd
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
volumes:
  elasticsearch_data:
