version: "3.6"

services:
  app:
    image: zwilson/jobs
    build: .
    volumes:
      - ./app:/usr/src/app
      - ./configs/scrapy/scrapy.cfg:/usr/src/scrapy.cfg
      - ./items:/usr/src/items
    depends_on:
      - scrapyd
    command: scrapyd-deploy
  scrapyd:
    image: zwilson/docker-scrapyd
    ports:
      - 6800:6800
    volumes:
      - ./items:/usr/src/items
      - ./configs/scrapyd/scrapyd.conf:/etc/scrapyd/scrapyd.conf
  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    ports:
      - 5601:5601
    depends_on:
        - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.1
