services:
  app:
    build:
      context:   .
    command:     scrapyd
    depends_on:
      - elasticsearch
      - splash
    image:       zwilson/jobs
    volumes:
      - ./app:/usr/src/app:rw
      - ./configs/app/scrapy.cfg:/usr/src/scrapy.cfg:ro
      - ./configs/app/scrapyd.conf:/usr/src/scrapyd.conf:ro
      - ./data/app/dbs:/usr/src/dbs:rw
      - ./data/app/eggs:/usr/src/eggs:rw
      - ./data/app/items:/usr/src/items:rw
      - ./logs/app:/usr/src/logs:rw
  elasticsearch:
    image:       docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    depends_on:
      - elasticsearch
    image:       docker.elastic.co/kibana/kibana:6.3.2
  proxy:
    image: nginx
    ports:
      - 5602:80
    volumes:
      - ./configs/proxy/default.conf:/etc/nginx/conf.d/default.conf
  splash:
    image:       scrapinghub/splash
version:         '3.6'
volumes:
    elasticsearch_data:
