version: '3'

services:
  app:
    image: zwilson/job
    build: https://github.com/zazazack/jobs.git
    ports:
      - 80:80
    volumes:
      - ./app:/usr/src/app
    command: scrapy crawl indeed
