configs:
  scrapy.cfg:
    file:             ./configs/app/scrapy.cfg
  scrapyd.conf:
    file:             ./configs/app/scrapyd.conf
  default.conf:
    file:             ./configs/proxy/default.conf
networks:
  backend:
    attachable:       true
  frontend:
    attachable:       true
services:
  app:
    command:          scrapyd
    configs:
      - source:       scrapy.cfg
        target:       /usr/src/scrapy.cfg
      - source:       scrapyd.conf
        target:       /usr/src/scrapyd.cfg
    depends_on:
      - elasticsearch
    environment:
      LOG_LEVEL:      INFO
    image:            zwilson/jobs
    networks:
      - backend
    volumes:
      - app_logs:/usr/src/logs
      - app_data:/usr/src/dbs
      - app_data:/usr/src/eggs
      - app_data:/usr/src/items
  elasticsearch:
    image:            docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    networks:
      - backend
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  # logstash:
  #   image:          docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  kibana:
    depends_on:
      - elasticsearch
    image:            docker.elastic.co/kibana/kibana:6.3.2
    networks:
      - frontend
      - backend
  proxy:
    configs:
      - source:       default.conf
        target:       /etc/nginx/conf.d/default.conf
    image:            nginx
    ports:
      - 5602:80
    networks:
      - frontend
version:              '3.6'
volumes:
  app_data:
  app_logs:
  elasticsearch_data:
