version: "3.6"
networks:
  backend:
    attachable: true
services:
  splash:
    image: scrapinghub/splash
    networks:
      - backend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      xpack.monitoring.collection.enabled: "true"
    networks:
      - backend
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
volumes:
  elasticsearch_data:
